"""users_data

Revision ID: 60520d573be1
Revises: 12b15bd3e982
Create Date: 2020-05-10 00:56:04.339593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60520d573be1'
down_revision = '12b15bd3e982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_table',
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('password', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('active IN (0, 1)'),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###
